<?php

namespace Paztek\Bundle\HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FruitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FruitRepository extends EntityRepository
{
}
